### ISSUE TITLE
TypeError: compute_class_weight() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by turian** [mrjleo/boilernet#13]
I am trying to replicate the README, but I get the following error:

```
!git clone https://github.com/mrjleo/boilernet.git
%cd boilernet
# Google Trends 2017
!gdown "https://drive.google.com/uc?id=1jkc6RC9_VmG8_-XBlk5A3FkZsx_v4k_Y"
!mkdir googletrends-2017 && cd googletrends-2017 && unzip ../googletrends-2017.zip
!python3 net/preprocess.py googletrends-2017/prepared_html/ -s googletrends-2017/50-30-100-split/ -w 1000 -t 50 --save googletrends_data
!python3 net/train.py googletrends_data --working_dir googletrends_train -l 2 -u 256 -d 0.5 -s 256 -e 50 -b 16 --interval 1

2022-08-10 11:37:01.140204: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Traceback (most recent call last):
  File "net/train.py", line 110, in <module>
    main()
  File "net/train.py", line 82, in main
    class_weights = get_class_weights(train_set_file)
  File "net/train.py", line 44, in get_class_weights
    return class_weight.compute_class_weight('balanced', [0, 1], y_train)
TypeError: compute_class_weight() takes 1 positional argument but 3 were given
```

You can try this in colab here:
[https://colab.research.google.com/drive/1DxsXbfDjXEz8VkDLsgJOq8wZoiqCLrHK?usp=sharing](https://colab.research.google.com/drive/1DxsXbfDjXEz8VkDLsgJOq8wZoiqCLrHK?usp=sharing)

**Comment by turian** [comment]
This appears to work if you begin with:

```
!pip3 install tensorflow==2.1.0 numpy==1.17.3 tqdm==4.39.0 nltk==3.4.5 beautifulsoup4==4.8.1 html5lib==1.0.1 scikit-learn==0.21.3
```
