### ISSUE TITLE
Error following readme to preprocess

### ISSUE THREAD

**Issue by turian** [mrjleo/boilernet#17]
I have downloaded and unzip'ed googletrend to the appropriate subdir.

I run:
```
python3 net/preprocess.py googletrends-2017/prepared_html/ -s googletrends-2017/50-30-100-split/ -w 1000 -t 50 --save googletrends_data
```

but I get many errors.

p.s. What version of tensorflow should I be using?

```
error processing googletrends-2017/prepared_html/gt_57.html                     
error processing googletrends-2017/prepared_html/gt_7.html                      
error processing googletrends-2017/prepared_html/gt_16.html                     
error processing googletrends-2017/prepared_html/gt_41.html                     
error processing googletrends-2017/prepared_html/gt_161.html                    
error processing googletrends-2017/prepared_html/gt_82.html                     
error processing googletrends-2017/prepared_html/gt_136.html                    
error processing googletrends-2017/prepared_html/gt_94.html                     
error processing googletrends-2017/prepared_html/gt_120.html                    
error processing googletrends-2017/prepared_html/gt_177.html                    
error processing googletrends-2017/prepared_html/gt_100.html                    
error processing googletrends-2017/prepared_html/gt_157.html                    
error processing googletrends-2017/prepared_html/gt_141.html                    
error processing googletrends-2017/prepared_html/gt_116.html                    
error processing googletrends-2017/prepared_html/gt_36.html                     
error processing googletrends-2017/prepared_html/gt_61.html                     
error processing googletrends-2017/prepared_html/gt_77.html                     
error processing googletrends-2017/prepared_html/gt_98.html                     
error processing googletrends-2017/prepared_html/gt_20.html                     
error processing googletrends-2017/prepared_html/gt_21.html                     
error processing googletrends-2017/prepared_html/gt_76.html                     
error processing googletrends-2017/prepared_html/gt_99.html                     
error processing googletrends-2017/prepared_html/gt_60.html                     
error processing googletrends-2017/prepared_html/gt_37.html                     
error processing googletrends-2017/prepared_html/gt_117.html                    
error processing googletrends-2017/prepared_html/gt_140.html                    
error processing googletrends-2017/prepared_html/gt_156.html                    
error processing googletrends-2017/prepared_html/gt_101.html                    
error processing googletrends-2017/prepared_html/gt_176.html                    
error processing googletrends-2017/prepared_html/gt_121.html                    
error processing googletrends-2017/prepared_html/gt_95.html                     
error processing googletrends-2017/prepared_html/gt_137.html                    
error processing googletrends-2017/prepared_html/gt_83.html                     
error processing googletrends-2017/prepared_html/gt_160.html                    
error processing googletrends-2017/prepared_html/gt_40.html                     
error processing googletrends-2017/prepared_html/gt_17.html                     
error processing googletrends-2017/prepared_html/gt_6.html                      
error processing googletrends-2017/prepared_html/gt_56.html                     
error processing googletrends-2017/prepared_html/gt_106.html                    
error processing googletrends-2017/prepared_html/gt_151.html                    
error processing googletrends-2017/prepared_html/gt_147.html                    
error processing googletrends-2017/prepared_html/gt_110.html                    
error processing googletrends-2017/prepared_html/gt_30.html                     
error processing googletrends-2017/prepared_html/gt_67.html                     
error processing googletrends-2017/prepared_html/gt_88.html                     
error processing googletrends-2017/prepared_html/gt_71.html                     
error processing googletrends-2017/prepared_html/gt_26.html                     
error processing googletrends-2017/prepared_html/gt_51.html                     
error processing googletrends-2017/prepared_html/gt_1.html                      
error processing googletrends-2017/prepared_html/gt_10.html                     
error processing googletrends-2017/prepared_html/gt_47.html                     
error processing googletrends-2017/prepared_html/gt_167.html                    
error processing googletrends-2017/prepared_html/gt_84.html                     
error processing googletrends-2017/prepared_html/gt_130.html                    
error processing googletrends-2017/prepared_html/gt_92.html                     
error processing googletrends-2017/prepared_html/gt_126.html                    
error processing googletrends-2017/prepared_html/gt_171.html                    
error processing googletrends-2017/prepared_html/gt_170.html                    
error processing googletrends-2017/prepared_html/gt_127.html                    
error processing googletrends-2017/prepared_html/gt_93.html                     
error processing googletrends-2017/prepared_html/gt_131.html                    
error processing googletrends-2017/prepared_html/gt_85.html                     
error processing googletrends-2017/prepared_html/gt_166.html                    
error processing googletrends-2017/prepared_html/gt_46.html                     
error processing googletrends-2017/prepared_html/gt_11.html                     
error processing googletrends-2017/prepared_html/gt_50.html                     
error processing googletrends-2017/prepared_html/gt_27.html                     
error processing googletrends-2017/prepared_html/gt_70.html                     
error processing googletrends-2017/prepared_html/gt_66.html                     
error processing googletrends-2017/prepared_html/gt_89.html                     
error processing googletrends-2017/prepared_html/gt_31.html                     
error processing googletrends-2017/prepared_html/gt_111.html                    
error processing googletrends-2017/prepared_html/gt_146.html                    
error processing googletrends-2017/prepared_html/gt_150.html                    
error processing googletrends-2017/prepared_html/gt_107.html                    
error processing googletrends-2017/prepared_html/gt_24.html                     
error processing googletrends-2017/prepared_html/gt_73.html                     
error processing googletrends-2017/prepared_html/gt_128.html                    
error processing googletrends-2017/prepared_html/gt_65.html                     
error processing googletrends-2017/prepared_html/gt_32.html                     
error processing googletrends-2017/prepared_html/gt_169.html                    
error processing googletrends-2017/prepared_html/gt_49.html                     
error processing googletrends-2017/prepared_html/gt_112.html                    
error processing googletrends-2017/prepared_html/gt_145.html                    
error processing googletrends-2017/prepared_html/gt_153.html                    
error processing googletrends-2017/prepared_html/gt_104.html                    
error processing googletrends-2017/prepared_html/gt_173.html                    
error processing googletrends-2017/prepared_html/gt_28.html                     
error processing googletrends-2017/prepared_html/gt_124.html                    
error processing googletrends-2017/prepared_html/gt_90.html                     
error processing googletrends-2017/prepared_html/gt_132.html                    
error processing googletrends-2017/prepared_html/gt_86.html                     
error processing googletrends-2017/prepared_html/gt_69.html                     
error processing googletrends-2017/prepared_html/gt_165.html                    
error processing googletrends-2017/prepared_html/gt_45.html                     
error processing googletrends-2017/prepared_html/gt_149.html                    
error processing googletrends-2017/prepared_html/gt_12.html                     
error processing googletrends-2017/prepared_html/gt_3.html                      
error processing googletrends-2017/prepared_html/gt_108.html                    
error processing googletrends-2017/prepared_html/gt_53.html                     
error processing googletrends-2017/prepared_html/gt_52.html                     
error processing googletrends-2017/prepared_html/gt_109.html                    
error processing googletrends-2017/prepared_html/gt_2.html                      
error processing googletrends-2017/prepared_html/gt_13.html                     
error processing googletrends-2017/prepared_html/gt_148.html                    
error processing googletrends-2017/prepared_html/gt_44.html                     
error processing googletrends-2017/prepared_html/gt_164.html                    
error processing googletrends-2017/prepared_html/gt_87.html                     
error processing googletrends-2017/prepared_html/gt_68.html                     
error processing googletrends-2017/prepared_html/gt_133.html                    
error processing googletrends-2017/prepared_html/gt_91.html                     
error processing googletrends-2017/prepared_html/gt_125.html                    
error processing googletrends-2017/prepared_html/gt_29.html                     
error processing googletrends-2017/prepared_html/gt_172.html                    
error processing googletrends-2017/prepared_html/gt_105.html                    
error processing googletrends-2017/prepared_html/gt_152.html                    
error processing googletrends-2017/prepared_html/gt_144.html                    
error processing googletrends-2017/prepared_html/gt_113.html                    
error processing googletrends-2017/prepared_html/gt_48.html                     
error processing googletrends-2017/prepared_html/gt_168.html                    
error processing googletrends-2017/prepared_html/gt_33.html                     
error processing googletrends-2017/prepared_html/gt_64.html                     
error processing googletrends-2017/prepared_html/gt_129.html                    
error processing googletrends-2017/prepared_html/gt_72.html                     
error processing googletrends-2017/prepared_html/gt_25.html                     
error processing googletrends-2017/prepared_html/gt_175.html                    
error processing googletrends-2017/prepared_html/gt_122.html                    
error processing googletrends-2017/prepared_html/gt_96.html                     
error processing googletrends-2017/prepared_html/gt_79.html                     
error processing googletrends-2017/prepared_html/gt_134.html                    
error processing googletrends-2017/prepared_html/gt_80.html                     
error processing googletrends-2017/prepared_html/gt_163.html                    
error processing googletrends-2017/prepared_html/gt_38.html                     
error processing googletrends-2017/prepared_html/gt_118.html                    
error processing googletrends-2017/prepared_html/gt_43.html                     
error processing googletrends-2017/prepared_html/gt_14.html                     
error processing googletrends-2017/prepared_html/gt_159.html                    
error processing googletrends-2017/prepared_html/gt_5.html                      
error processing googletrends-2017/prepared_html/gt_55.html                     
error processing googletrends-2017/prepared_html/gt_22.html                     
error processing googletrends-2017/prepared_html/gt_179.html                    
error processing googletrends-2017/prepared_html/gt_75.html                     
error processing googletrends-2017/prepared_html/gt_63.html                     
error processing googletrends-2017/prepared_html/gt_138.html                    
error processing googletrends-2017/prepared_html/gt_34.html                     
error processing googletrends-2017/prepared_html/gt_180.html                    
error processing googletrends-2017/prepared_html/gt_114.html                    
error processing googletrends-2017/prepared_html/gt_18.html                     
error processing googletrends-2017/prepared_html/gt_143.html                    
error processing googletrends-2017/prepared_html/gt_9.html                      
error processing googletrends-2017/prepared_html/gt_155.html                    
error processing googletrends-2017/prepared_html/gt_59.html                     
error processing googletrends-2017/prepared_html/gt_102.html                    
error processing googletrends-2017/prepared_html/gt_103.html                    
error processing googletrends-2017/prepared_html/gt_58.html                     
error processing googletrends-2017/prepared_html/gt_154.html                    
error processing googletrends-2017/prepared_html/gt_8.html                      
error processing googletrends-2017/prepared_html/gt_142.html                    
error processing googletrends-2017/prepared_html/gt_19.html                     
error processing googletrends-2017/prepared_html/gt_115.html                    
error processing googletrends-2017/prepared_html/gt_35.html                     
error processing googletrends-2017/prepared_html/gt_139.html                    
error processing googletrends-2017/prepared_html/gt_62.html                     
error processing googletrends-2017/prepared_html/gt_74.html                     
error processing googletrends-2017/prepared_html/gt_178.html                    
error processing googletrends-2017/prepared_html/gt_23.html                     
error processing googletrends-2017/prepared_html/gt_54.html                     
error processing googletrends-2017/prepared_html/gt_4.html                      
error processing googletrends-2017/prepared_html/gt_158.html                    
error processing googletrends-2017/prepared_html/gt_15.html                     
error processing googletrends-2017/prepared_html/gt_42.html                     
error processing googletrends-2017/prepared_html/gt_119.html                    
error processing googletrends-2017/prepared_html/gt_39.html                     
error processing googletrends-2017/prepared_html/gt_162.html                    
error processing googletrends-2017/prepared_html/gt_81.html                     
error processing googletrends-2017/prepared_html/gt_135.html                    
error processing googletrends-2017/prepared_html/gt_97.html                     
error processing googletrends-2017/prepared_html/gt_78.html                     
error processing googletrends-2017/prepared_html/gt_123.html                    
error processing googletrends-2017/prepared_html/gt_174.html                    
100%|██████████████████████████████████████| 180/180 [00:00<00:00, 13148.29it/s]
Traceback (most recent call last):
  File "/Users/joseph/dev/boilernet/net/preprocess.py", line 214, in <module>
    main()
  File "/Users/joseph/dev/boilernet/net/preprocess.py", line 203, in main
    train_set = [data[basename] for basename in read_file(train_set_file)]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph/dev/boilernet/net/preprocess.py", line 203, in <listcomp>
    train_set = [data[basename] for basename in read_file(train_set_file)]
                 ~~~~^^^^^^^^^^
KeyError: 'gt_41.html'
```

**Comment by turian** [comment]
Had to pip3 install requirements.txt (and pip install html5lib manually, despite it being there)
