### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by mazzespazze** [mrjleo/boilernet#7]
Hello,

I'm trying to reproduce your results but I get stuck quite early in the process. The steps I did so far are:

`git clone https://github.com/mrjleo/boilernet.git`

Then I open the project with PyCharm that install all the dependencies according to your _requirements.txt_

Then I enter in the "Run Configuration" of the file net/preprocess.py and I set it as in the example such that:
`python3 net/preprocess.py google-trends/prepared_html/ -s google-trends/50-30-100-split/ -w 1000 -t 50 --save googletrends_data`

But on the PyCharm console I get the following error:

```
2020-12-23 23:30:24.079689: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-12-23 23:30:24.080624: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-12-23 23:30:24.080631: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

Traceback (most recent call last):
  File "/boilernet/net/preprocess.py", line 211, in <module>
    main()
  File "/boilernet/net/preprocess.py", line 200, in main
    train_set = [data[basename] for basename in read_file(train_set_file)]
  File "/boilernet/net/preprocess.py", line 200, in <listcomp>
    train_set = [data[basename] for basename in read_file(train_set_file)]
KeyError: 'gt_41.html'
error processing /boilernet/google-trends/prepared_html/gt_105.html

Process finished with exit code 1
```

I tried to run it also directly from the terminal installing manually your requirements, but I end up with the exact same error.

**Comment by mrjleo** [comment]
Hi, there seems to be a problem processing one of the pages. Maybe you are missing some files required by NLTK for tokenization (they have to be manually downloaded). If that's the case, please try if running the following solves your problem:

`python3 -c "import nltk; nltk.download('punkt')"`

**Comment by mazzespazze** [comment]
It was that! I added the line

`nltk.download('punkt')`

In `preprocess.py` file. Then it pre-process and train the model as you say in the ReadMe. 

Thanks!
